/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\languages.gltf
*/

import { useGLTF } from '@react-three/drei'

export default function Languages(props) {
  const { nodes, materials } = useGLTF('./models/languages.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.018']} rotation={[Math.PI / 2, 0, 0]} scale={[600, 400, 600]} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.018']} rotation={[Math.PI / 2, 0, 0]} scale={[600, 400, 600]} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.018']} rotation={[Math.PI / 2, 0, 0]} scale={[600, 400, 600]} />
    </group>
  )
}

useGLTF.preload('./models/languages.gltf')
